### ISSUE TITLE
Does this work with haml?

### ISSUE THREAD

**Issue by mb-dev** [rails/cache_digests#8] opened 2012-10-31 03:48 UTC
I am having trouble getting this to work. I update the partial but the caching is still not refreshing. 

Let me know if this is compatible with haml and i'll post some code snippets.

**Comment by dhh** [comment] 2012-10-31 08:08
This has not been tested with haml, so if its not working, it'll need someone who cares to work on that to look into it.

**Comment by pokonski** [comment] 2012-10-31 08:24
@ddh was it tested with ERB only? Because I'm willing to take a look into HAML/Slim issues.

**Comment by Arjeno** [comment] 2012-10-31 08:37
I can confirm it's working with Slim. Although not in development mode.

**Comment by dhh** [comment] 2012-10-31 08:37
Yes, and jbuilder. Please do investigate.

**Comment by azul** [comment] 2012-11-03 09:47
Does not seem to work with haml for me either. Adding content in the template that has the cache line will not expire the cache in development.

**Comment by ready4god2513** [comment] 2012-12-06 00:19
Do we have any movement on this?  If not, it is something that I would be interested in looking in to.

**Comment by dhh** [comment] 2012-12-06 07:23
I haven't heard of any. Have at it!

**Comment by dasch** [comment] 2012-12-08 17:21
Could the dependency tracking be moved to the template handlers, perchance? That way, each handler could go about it its own way.

**Comment by balexand** [comment] 2012-12-12 00:27
I'm using cache_digests with HAML and the only issue I can find is fixed in #21. I also created tests in #22. I included the tests separately, since I'm not sure if @dhh will want the added complexity in the test suite. This issue can be closed after #21 is merged.

**Comment by balexand** [comment] 2013-02-13 18:21
This issue can be closed now that #34 has been merged. /cc @rafaelfranca

**Comment by rafaelfranca** [comment] 2013-02-13 18:22
Yes. Thank you

**Closed as completed by rafaelfranca** 2013-02-13 18:22 UTC

**Comment by phuongnd08** [comment] 2013-06-18 11:01
I'm using `cache_digests (0.3.1)` with haml right now and `rake  cache_digests:dependencies` still returns empty array all the time. I even put this in initializer: `CacheDigests::DependencyTracker.register_tracker :haml, CacheDigests::DependencyTracker::ERBTracker`.

**Comment by azul** [comment] 2014-11-29 14:48
@phuongnd08 same thing here. Have you been able to fix it?

**Comment by phuongnd08** [comment] 2014-11-30 04:18
I switched over to AngularJS a while back so we no longer need html fragment caching.

**Comment by azul** [comment] 2014-11-30 09:51
Turns out i still lacked the initializer and with the initializer it works for me now.
Thanks for the quick reply never the less, @phuongnd08. :smile:

**Comment by jjb** [comment] 2015-01-19 03:41
as of https://github.com/indirect/haml-rails/pull/51/, haml-rails will automagically do this
